version: '2'

volumes:
  assets:
  media:

services:

  postgres:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: pootle
      POSTGRES_PASSWORD: cNEujap1w6OMSDGDIeE5TYS7aKl
      POSTGRES_DB: pootle

  elasticsearch:
    image: elasticsearch
    hostname: elasticsearch

  redis:
    image: redis
    hostname: redis

  nginx:
    image: nginx
    hostname: nginx
    links:
      - pootle
    volumes:
      - ./nginx/pootle-http.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - assets:/var/www/pootle/assets
      - media:/var/www/pootle/media

  pootle:
    build:
      context: .
    command: [
      'uwsgi',
      '--master',
      '--http', '0.0.0.0:8000',
      '--wsgi-file', '/etc/pootle/wsgi.py',
      '--callable', 'application'
    ]
    volumes:
      - ./wsgi.py:/etc/pootle/wsgi.py
      - ./pootle.conf:/etc/pootle/pootle.conf
      - assets:/var/www/pootle/assets
      - media:/var/www/pootle/media
    environment: &app_env
      DJANGO_SETTINGS_MODULE: "pootle.settings"
      POOTLE_SETTINGS: "/etc/pootle/pootle.conf"
    depends_on:
      - postgres
      - redis
      - elasticsearch

  rqworker:
    build:
      context: .
    command: ['pootle', 'rqworker']
    depends_on:
      - pootle
    volumes_from:
      - pootle
    environment:
      <<: *app_env
